LibraryDataAccess/LibraryWebSite/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryBusinessLogicLayer;
using LibraryCommon;
using LibraryWebSite.Models;

namespace LibraryWebSite.Controllers
{
    public class BookController : Controller
    {

        // this is the server paging index
        public ActionResult Page(int page, int count)
        {
            try
            {
                if (page <=0)
                {
                    page = 1;
                }
                ViewBag.PageNumber = page;
                ViewBag.PageSize = count;
                using (Context ctx = new Context())
                {
                    ViewBag.TotalCount = ctx.BookObtainCount();
                    var data = VMBook.ToList(ctx.BookGetAll((page-1)*count, count));

                    return View(data);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }


        public ActionResult AjaxLoading()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

            int skip = (start != null) ? Convert.ToInt32(start) : 0;
            int take = (length != null) ? Convert.ToInt32(length) : 1;
            int totalRecordCount = 0;
            using (Context ctx = new Context())
            {
                totalRecordCount = ctx.BookObtainCount();
                var Data = ctx.BookGetAll();
                IOrderedEnumerable<Book> SortedData;
                if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                {
                    if (sortColumnDir == "asc")
                    {
                        switch(sortColumn.ToLower())
                        {
                            case ("isbn"):
                                SortedData = Data.OrderBy(x => x.ISBN);
                                break;
                            case ("bookname"):
                                SortedData = Data.OrderBy(x => x.BookName);
                                break;
                            case ("pages"):
                                SortedData = Data.OrderBy(x => x.Pages);
                                break;
                            case ("daysoverdue"):
                                SortedData = Data.OrderBy(x => x.DaysOverdue);
                                break;
                            case ("genrename"):
                                SortedData = Data.OrderBy(x => x.GenreName);
                                break;
                            default:
                                SortedData = Data.OrderBy(x => x.BookName);
                                break;
                                
                        }
                    }
                    else
                    {
                        switch (sortColumn.ToLower())
                        {
                            case ("isbn"):
                                SortedData = Data.OrderByDescending(x => x.ISBN);
                                break;
                            case ("bookname"):
                                SortedData = Data.OrderByDescending(x => x.BookName);
                                break;
                            case ("pages"):
                                SortedData = Data.OrderByDescending(x => x.Pages);
                                break;
                            case ("daysoverdue"):
                                SortedData = Data.OrderByDescending(x => x.DaysOverdue);
                                break;
                            case ("genrename"):
                                SortedData = Data.OrderByDescending(x => x.GenreName);
                                break;
                            default:
                                SortedData = Data.OrderByDescending(x => x.BookName);
                                break;

                        }
                    }
                  
                }
                else
                {
                    SortedData = (IOrderedEnumerable<Book>) Data;
                }
                //Search 
                IEnumerable<Book> FilteredAndSortedData;
                if (!string.IsNullOrEmpty(searchValue))
                {

                    FilteredAndSortedData = SortedData.Where
                        (
                        x => ((x.ISBN != null && x.ISBN.Contains(searchValue)) |
                              ((x.BookName != null) && x.BookName.Contains(searchValue)) |
                              ((x.GenreName != null) && x.GenreName.Contains(searchValue))

                             )    
                        );
                         
                }
                else
                {
                    FilteredAndSortedData = SortedData;
                }
                List<Book> FinalData = FilteredAndSortedData.ToList();
                int FilteredCount = FinalData.Count;
                return Json(new { draw = draw, recordsTotal = totalRecordCount,
                    recordsFiltered = FilteredCount,
                    data = FinalData.Skip(skip).Take(take),
                });
            }

           
        }


        public ActionResult AjaxFastLoading()
        {
            var draw = Request.Form.GetValues("draw").FirstOrDefault();
            var start = Request.Form.GetValues("start").FirstOrDefault();
            var length = Request.Form.GetValues("length").FirstOrDefault();
            var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
            var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
            var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();

            int skip = (start != null) ? Convert.ToInt32(start) : 0;
            int take = (length != null) ? Convert.ToInt32(length) : 1;
            int totalRecordCount = 0;
            using (Context ctx = new Context())
            {
                totalRecordCount = ctx.BookObtainCount();
                var Data = ctx.BookGetSortedAndFiltered(sortColumn,sortColumnDir,searchValue,skip,take);


                int FilteredCount = ctx.BookGetSortedAndFilteredCount(sortColumn, sortColumnDir, searchValue) ;
                return Json(new
                {
                    draw = draw,
                    recordsTotal = totalRecordCount,
                    recordsFiltered = FilteredCount,
                    data = Data,
                });
            }


        }

        public ActionResult AjaxIndex()
        {
            return View();
        }

        public ActionResult AjaxAdvancedIndex()
        {
            return View();
        }
        public ActionResult Index()
        {
            return View();
        }
        // GET: Book
        [MustBeInTheRole("List:Books")]
        public ActionResult AllIndex(int id)
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var data = VMBook.ToList(ctx.BookGetAll(0,id));
                    return View(data);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

 

        // GET: Book/Details/5
        [MustBeInTheRole("View:Book")]
        public ActionResult Details(int id)
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var data = VMBook.MakeNew(ctx.BookFindByID(id));
                    return View(data);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // GET: Book/Create

        [MustBeInTheRole("Create:Book")]
        public ActionResult Create()
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var data = new VMBook();
                    data.PopulateGenreItems(ctx.GenreGetAll());
                    return View(data);
                }

            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // POST: Book/Create
        [MustBeInTheRole("Create:Book")]
        [HttpPost]
        public ActionResult Create(VMBook data)
        {
            try
            {
                using (Context ctx = new Context())
                {
                    if (ModelState.IsValid)
                    {
                        ctx.BookCreate(data);
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        data.PopulateGenreItems(ctx.GenreGetAll());
                        return View(data);
                    }
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // GET: Book/Edit/5
        [MustBeInTheRole("Edit:Book")]
        public ActionResult Edit(int id)
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var data = VMBook.MakeNew(ctx.BookFindByID(id));

LibraryDataAccess/LibraryWebSite/Controllers/ExceptionController.cs
using LibraryBusinessLogicLayer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryWebSite.Controllers
{
    public class ExceptionController : Controller
    {
        // GET: Exception
        public ActionResult Index()
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var items = ctx.LogItemGetAll();
                    return View(items);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
      
        }

        public ActionResult Details(int id)
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var item = ctx.LogItemFindByID(id);
                    if (null == item)
                    {
                        return View("NotFound");
                    }
                    return View(item);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }

        }

    }
}

LibraryDataAccess/LibraryWebSite/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LibraryBusinessLogicLayer;
using LibraryCommon;
using LibraryWebSite.Models;

namespace LibraryWebSite.Controllers
{
    public class RoleController : Controller
    {
        // GET: Role
        public ActionResult Index()
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var data = Models.VMRole.ToList(ctx.RoleGetAll());
                    return View(data);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // GET: Role/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var data = Models.VMRole.MakeNew(ctx.RoleFindByID(id));
                    return View(data);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // GET: Role/Create
        public ActionResult Create()
        {
            try
            {

                var data = new VMRole();
                return View(data);

            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // POST: Role/Create
        [HttpPost]
        public ActionResult Create(VMRole data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Context ctx = new Context())
                    {
                        ctx.RoleCreate(data);
                        return RedirectToAction("Index");
                    }
                }

                return View(data);
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // GET: Role/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var data = Models.VMRole.MakeNew(ctx.RoleFindByID(id));
                    return View(data);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // POST: Role/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, VMRole data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Context ctx = new Context())
                    {
                        ctx.RoleUpdateJust(id, data);
                        // since we just changed a role, should also update the
                        // current users role string so they are able to use
                        // the new role info instantly
                        // other users will have to log out and log back in
                        Borrower b = Authentication.GetCurrentUser(ctx);
                       
                        Session["AUTHRole"] = ctx.GetRoleString(b);
                        return RedirectToAction("Index");
                    }

                }
                return View(data);
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // GET: Role/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                using (Context ctx = new Context())
                {
                    var data = Models.VMRole.MakeNew(ctx.RoleFindByID(id));
                    return View(data);
                }
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }

        // POST: Role/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, VMRole data)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    using (Context ctx = new Context())
                    {
                        ctx.RoleDelete(id);
                        return RedirectToAction("Index");
                    }

                }
                return View(data);
            }
            catch (Exception ex)
            {
                return View("Exception", ex);
            }
        }
    }
}

LibraryDataAccess/LibraryWebSite/Views/Shared/Exception.cshtml
@model Exception
@{
    ViewBag.Title = "Exception";


    // this calls the version returning the id to present in message
    int id = Logging.Logger.Log(Model, "MVC", 0);
}

<h2>Exception</h2>
@if (Hide.UnlessInTheRole("View:Exception"))
{
    <text>
    The following Exception occurred
<hr />
Log id:  @id<hr />
<p>@Model</p>
</text>
}
else
{
<text>
    An unexpected error occured, please contact your support.  The log Identifier is: @id;
</text>
}

LibraryDataAccess/LibraryWebSite/Views/Shared/ItemNotFound.cshtml
@{
    ViewBag.Title = "ItemNotFound";
}

<h2>ItemNotFound</h2>


The Item you were looking for was not found in our database

LibraryDataAccess/LibraryWebSite/Views/Shared/LoginRegisterPartial.cshtml
@if (User.Identity.IsAuthenticated)
{
    string data = User.Identity.AuthenticationType;
    string username = User.Identity.Name;

    <li>@Html.ActionLink(data, "Verify", "Home")</li>
    <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
}
else
{
    <li>@Html.ActionLink("Register", "Register", "Home")</li>
    <li>@Html.ActionLink("Login", "Login", "Home")</li>
}

LibraryDataAccess/LibraryWebSite/Views/Shared/NotAllowed.cshtml
@{
    ViewBag.Title = "NotAllowed";
}

<h2>NotAllowed</h2>

The operation you are attempting is not allowed.

LibraryDataAccess/LibraryWebSite/Views/Shared/Paging.cshtml
@{
    int PageNumber = ViewBag.PageNumber;
    int PageSize = ViewBag.PageSize;
    int TotalCount = ViewBag.TotalCount;
    int TotalPageButtonCount = ((0 == TotalCount % PageSize) ? 0 : 1) + TotalCount / PageSize;
    int ActualButtonCount = (10 < TotalPageButtonCount) ? 10 : TotalPageButtonCount;
    int number =  TotalPageButtonCount - ActualButtonCount ;

}
<p>
    Items Per Page:
    @Html.ActionLink(" -1- ", "page", new { page = 1, count = 1 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -2- ", "page", new { page = 1, count = 2 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -3- ", "page", new { page = 1, count = 3 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -4- ", "page", new { page = 1, count = 4 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -5- ", "page", new { page = 1, count = 5 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -10- ", "page", new { page = 1, count = 10 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -20- ", "page", new { page = 1, count = 20 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -30- ", "page", new { page = 1, count = 30 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -40- ", "page", new { page = 1, count = 40 })
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    @Html.ActionLink(" -50- ", "page", new { page = 0, count = 50 })

</p>
<p>
    @{
        for (int i = 1; i <= ActualButtonCount; i++)
        {
            string classstring = (i == PageNumber) ? "btn btn-sm btn-success glyphicon glyphicon-star-empty" : "btn btn-sm btn-normal glyphicon glyphicon-asterisk";
            @Html.ActionLink($"-Page {i}-", "Page", new { page = i, count = PageSize }, new { @class = classstring });

        }
        if (ActualButtonCount != TotalPageButtonCount)
        {
            <text> @number Buttons Truncated</text>
        }
    }
</p>

LibraryDataAccess/LibraryWebSite/Views/Shared/_Layout.cshtml
@using LibraryWebSite.Models;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top col-md-12">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    @if (Hide.UnlessInTheRole("List:Author"))
                    {
                        <li>@Html.ActionLink("Authors", "Index", "Author")</li>
                    }
                    @if (Hide.UnlessInTheRole("List:Book"))
                    {
                        <li>@Html.ActionLink("Books", "Index", "Book")</li>
                    }
                    @if (Hide.UnlessInTheRole("List:Borrower"))
                    {
                        <li>@Html.ActionLink("Borrowers", "Index", "Borrower")</li>
                    }
                    @if (Hide.UnlessInTheRole("List:Genre"))
                    {
                        <li>@Html.ActionLink("Genres", "Index", "Genre")</li>
                    }
                    @if (Hide.UnlessInTheRole("List:Author"))
                    {
                        <li>@Html.ActionLink("Roles", "Index", "Role")</li>
                    }
                    @if (Hide.UnlessInTheRole("List:ThisUserBorrowing"))
                    {
                        <li>@Html.ActionLink("My Borrowed Books", "MyBorrowedBooks", "Book")</li>
                    }
                    @if (Hide.UnlessInTheRole("List:AllUserBorrowing"))
                    {
                        <li>@Html.ActionLink("All Borrowed Books", "AllBorrowedBooks", "Book")</li>
                    }
                    @if (Hide.UnlessInTheRole("View:Reporting"))
                    {
                        <li>@Html.ActionLink("Reports", "index", "Reporting")</li>
                    }

                    <li>@Html.ActionLink("View Exceptions", "index", "Exception")</li>


                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated && !Authentication.isHashed())
                    {
                        <li>@Html.ActionLink("Hash my Cleartext Password", "HashAccount", "Home")</li>
                    }
                    @{Html.RenderPartial("LoginRegisterPartial"); }
                </ul>
            </div>
        </div>
    </div>
 
      

    <div class="container body-content">
        <p>.</p><p>.</p><p>.</p><p>.</p>
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>